### ISSUE TITLE
update README.md - missing community.general in Requirements

### ISSUE THREAD

**Issue by nayodahl** [geerlingguy/ansible-role-ntp#115]
I think the readme is outdated, there is no "community.general" in Requirements.

When I try to ansible-lint a playbook using geerlingguy/ntp, I get the following error : 

`../../../../home/runner/.cache/ansible-compat/70d583/roles/geerlingguy.ntp/tasks/main.yml:36:3: syntax-check: couldn't resolve module/action 'timezone'. This often indicates a misspelling, missing collection, or incorrect module path.`

in tasks/main : 

```
- name: Set timezone.
  timezone:
    name: "{{ ntp_timezone }}"
  notify: restart cron
```

 
  Indeed, the timezone command does not exist unless you install community.general, according to this doc : https://docs.ansible.com/ansible/latest/collections/community/general/timezone_module.html
