### ISSUE TITLE
Setting local time fails with Permission Denied

### ISSUE THREAD

**Issue by bgerstle** [geerlingguy/ansible-role-ntp#12]
```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [testing]

TASK [geerlingguy.ntp : Include OS-specific variables.] ************************
ok: [testing]

TASK [geerlingguy.ntp : Set the correct timezone.] *****************************
fatal: [testing]: FAILED! => {"changed": false, "failed": true, "gid": 0, "group": "root", "mode": "0644", "msg": "Error while replacing: [Errno 13] Permission denied", "owner": "root", "path": "/etc/localtime", "size": 118, "state": "file", "uid": 0}
```

Playbook:

``` yaml
---
- hosts: all
  roles:
    - { role: geerlingguy.ntp,
        ntp_enabled: true,
        ntp_timezone: Etc/UTC,
        ntp_servers: [
          server 0.amazon.pool.ntp.org iburst
          server 1.amazon.pool.ntp.org iburst,
          server 2.amazon.pool.ntp.org iburst,
          server 3.amazon.pool.ntp.org iburst
        ],
        tags: ["provision"]
      }
```

Config:

```
[defaults]
remote_user=ubuntu

[ssh_connection]
ssh_args = -o ForwardAgent=yes
```
