### ISSUE TITLE
Error on Debian on first check_mode run

### ISSUE THREAD

**Issue by Al-thi** [geerlingguy/ansible-role-ntp#120]
Hello,

This role fails on Debian when playing the following tasks in check_mode on a fresh server : 
```yaml
- name: Ensure NTP is running and enabled as configured.
  service:
    name: "{{ ntp_daemon }}"
    state: started
    enabled: true
  when: ntp_enabled | bool

- name: Ensure NTP is stopped and disabled as configured.
  service:
    name: "{{ ntp_daemon }}"
    state: stopped
    enabled: false
  when: not (ntp_enabled | bool)
```

with the following error message : 
```
fatal: [xxx]: FAILED! => {"changed": false, "msg": "Could not find the requested service ntp: host"}
```

because ntp is not installed and therefore the systemd service state check fails.

I suggest adding the following line to these tasks to ignore check_mode errors : 
```yaml
  ignore_errors: "{{ ansible_check_mode }}"
```
