### ISSUE TITLE
Error `'ansible_system' is undefined`

### ISSUE THREAD

**Issue by Apollo3zehn** [geerlingguy/ansible-role-ntp#137]
I get the following error when trying to import the role:

```
FAILED! => {"msg": "The conditional check 'ansible_system == \"Linux\"' failed. The error was: error while evaluating conditional (ansible_system == \"Linux\"): 'ansible_system' is undefined. 'ansible_system' is undefined\n\nThe error appears to be in '/home/vincent/.ansible/roles/geerlingguy.ntp/tasks/main.yml': line 33, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Ensure tzdata package is installed (Linux).\n  ^ here\n"}
```

The reason is that in my `ansible.cfg` I have `INJECT_FACTS_AS_VARS=false` for security reasons. This means that there are no `ansible_`-prefixed variables. To avoid these kind issues, it is safer to use the original variable `ansible_facts.system` instead. My workaround for now is to define the missing variable (`services` is missing as well):

```yaml
    - name: Import role geerlingguy.ntp
      become: true
      ansible.builtin.import_role:
        name: geerlingguy.ntp
      vars:
        ansible_system: "{{ ansible_facts.system }}"
        services: "{{ x|default({}) }}"
```
