### ISSUE TITLE
Setting up chronyd in LXC

### ISSUE THREAD

**Issue by Runkar** [geerlingguy/ansible-role-ntp#142]
Hello!

I was using your role to setup my LXC but unfortunately chronyd is not starting because of permission errors. Chronyd is not permitted to modify system clock inside the container.
Although chronyd mostly is not active in virtualized environments in order to make it work you only need to make two changes to make it work:

- start chronyd with the "-x" flag to disable this functionality and
- drop the "CAP_SYS_TIME" in the systemd unit

Maybe you could include something like:

```` yaml
- name: Drop CAP_SYS_TIME in container environment
  ansible.builtin.blockinfile:
    path: /etc/systemd/system/chronyd.service.d/cap_drop.conf
    block: |
      [Unit]
      ConditionCapability=
    create: true
  when: ansible_virtualization_type == "lxc"
  notify: systemd daemon-reload

- name: Adding start parameter to chronyd in container environment
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/chronyd
    regexp: "^(OPTIONS=.*)$"
    line: 'OPTIONS="-F 2 -x"'
  when: ansible_virtualization_type == "lxc"
````
Thank you!
