### ISSUE TITLE
additional operating system for the role

### ISSUE THREAD

**Issue by vmpr** [geerlingguy/ansible-role-ntp#81]
Hi Jeff, I am maintaining a lot of hypervisor hosts and they are a bit different to normal operating systems. In that case, it's XCP-ng, which is an (awesome) fork of XenServer and Xenserver sits on top of centos. 
My problem is that when you check for 'ansible_os_family' my Server will not give you back 'RedHat' it will tell you that it is `"ansible_os_family": "XCP-ng",`

at the moment I've fixed that like:
```
  roles:
    # role to manage ntp/chrony
    - role: geerlingguy.ntp
      vars:
        ansible_os_family: 'RedHat'
```

but I would like to bring the XCP-ng OS in your role. it is actually an centos7 so it needs exactly the variable file which RedHat is using:

that should do the trick:
```
- name: Include OS-specific variables for XCP-ng.
  include_vars: RedHat.yml
  when:
    - ansible_os_family == 'XCP-ng'
```

so we don't need another File in the vars directory with the same values like RedHat.yml

I am happy to do a PR if that's the way you prefer or do you have a better idea?
thanks!
